### ISSUE TITLE
FC while saving GPX file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [billycris007/open-gpstracker#116]
```
java.lang.NullPointerException:
  at java.io.File.fixSlashes(File.java:267)
  at java.io.File.<init>(File.java:131)
  at nl.sogeti.android.gpstracker.actions.utils.GpxCreator.run(GpxCreator.java:235)
```

Original issue reported on code.google.com by `rcgr...@gmail.com` on 13 Jun 2010 at 9:25

**Comment by GoogleCodeExporter** [comment]
```
new update force closes on share or save to SD. Nexus one ??
```

Original comment by `rcgr...@gmail.com` on 23 Jul 2010 at 12:21

**Comment by GoogleCodeExporter** [comment]
```
Finally exception fixed, probably there is another exception in the try clause
```

Original comment by `rcgr...@gmail.com` on 25 Jul 2010 at 12:39
- Changed state: **Fixed**
