### ISSUE TITLE
NullPointerException in GPSLoggerService.requestLocationUpdates()

### ISSUE THREAD

**Issue by GoogleCodeExporter** [billycris007/open-gpstracker#150]
```
From market submitted report:

Caused by: java.lang.NullPointerException
at 
nl.sogeti.android.gpstracker.logger.GPSLoggerService.requestLocationUpdates(GPSL
oggerService.java:599)
at 
nl.sogeti.android.gpstracker.logger.GPSLoggerService.resumeLogging(GPSLoggerServ
ice.java:486)
at 
nl.sogeti.android.gpstracker.logger.GPSLoggerService.crashRestoreState(GPSLogger
Service.java:406)
at 
nl.sogeti.android.gpstracker.logger.GPSLoggerService.onCreate(GPSLoggerService.j
ava:355)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2959)
... 10 more
```

Original issue reported on code.google.com by `rcgr...@gmail.com` on 11 Oct 2010 at 5:45

**Comment by GoogleCodeExporter** [comment]
```
The handler object on the messageloop isnt yet created when the message to 
start logging is created....
```

Original comment by `rcgr...@gmail.com` on 11 Oct 2010 at 5:51

**Comment by GoogleCodeExporter** [comment]
Original comment by `rcgr...@gmail.com` on 11 Oct 2010 at 6:42
- Changed title: **NullPointerException in GPSLoggerService.requestLocationUpdates()**
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
semaphore added
```

Original comment by `rcgr...@gmail.com` on 11 Oct 2010 at 6:42

**Comment by GoogleCodeExporter** [comment]
```
Also at onDestroy nullpointers... 

java.lang.RuntimeException: Unable to stop service 
nl.sogeti.android.gpstracker.logger.GPSLoggerService@4618d068: 
java.lang.NullPointerException
at android.app.ActivityThread.handleStopService(ActivityThread.java:3309)
at android.app.ActivityThread.access$3700(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:144)
at android.app.ActivityThread.main(ActivityThread.java:4937)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at 
nl.sogeti.android.gpstracker.logger.GPSLoggerService.onDestroy(GPSLoggerService.
java:377)
at android.app.ActivityThread.handleStopService(ActivityThread.java:3295)
... 10 more
```

Original comment by `rcgr...@gmail.com` on 11 Oct 2010 at 7:22
